
const Data = [
	{
		id: 1,
		category: "education",
		icon: "fa-solid fa-graduation-cap icon-graduation",
		year: "2018",
		title: "10th Standard",
		desc: "John Milton Public School",
		grade: "81.2%",
	},
	{
		id: 2,
		category: "education",
		icon: "fa-solid fa-graduation-cap icon-graduation",
		year: "2020",
		title: "12th Standard",
		desc: "John Milton Public School",
		grade: "94.6%",
	},
	{
		id: 3,
		category: "education",
		icon: "fa-solid fa-graduation-cap icon-graduation",
		year: "2020 - Present",
		title: "B.Tech (Computer Science & Engineering)",
		desc: "Amity University, Noida",
		grade: "8.80 CGPA",
	},
	// {
	//   id: 4,
	//   category: "experience",
	//   icon: "icon-briefcase",
	//   year: "2019 - present",
	//   title: "Web Designer",
	//   desc: "Lorem ipsum dolor sit amet quo ei simul congue exerci     ad nec admodum perfecto.",
	// },
	// {
	//   id: 5,
	//   category: "experience",
	//   icon: "icon-briefcase",
	//   year: "2013 - 2017",
	//   title: "Front-End Developer",
	//   desc: "Lorem ipsum dolor sit amet quo ei simul congue exerci     ad nec admodum perfecto.",
	// },
	// {
	//   id: 6,
	//   category: "experience",
	//   icon: "icon-briefcase",
	//   year: "2009 - 2013",
	//   title: "Back-End Developer",
	//   desc: "Lorem ipsum dolor sit amet quo ei simul congue exerci     ad nec admodum perfecto.",
	// },
]
export default Data
